In [2]:
import numpy as np

In [5]:
vet = np.array([1, 2, 3, 6, 8, 9, 10, 11, 13, 14, 15, 101, 15, 13, 12, 3, 1])
vet

array([  1,   2,   3,   6,   8,   9,  10,  11,  13,  14,  15, 101,  15,
        13,  12,   3,   1])

In [7]:
type(vet)

numpy.ndarray

In [8]:
vet2 = np.array([1, 2, 3, 4, 5])
vet2.cumsum()

array([ 1,  3,  6, 10, 15])

In [11]:
print(vet[4])

8


In [12]:
vet[0] = -1
vet

array([ -1,   2,   3,   6,   8,   9,  10,  11,  13,  14,  15, 101,  15,
        13,  12,   3,   1])

In [15]:
vet = np.append(vet, 202)
vet

array([ -1,   2,   3,   6,   8,   9,  10,  11,  13,  14,  15, 101,  15,
        13,  12,   3,   1, 202])

In [16]:
vet = vet[:-1]
vet

array([ -1,   2,   3,   6,   8,   9,  10,  11,  13,  14,  15, 101,  15,
        13,  12,   3,   1])

In [17]:
vet = np.delete(vet, -2)
vet

array([ -1,   2,   3,   6,   8,   9,  10,  11,  13,  14,  15, 101,  15,
        13,  12,   1])

In [18]:
vet.shape

(16,)

In [19]:
vetor = np.array([[0, -5],[11, 300]])
vetor

array([[  0,  -5],
       [ 11, 300]])

In [20]:
vetor.shape

(2, 2)

In [22]:
vetor3x2 = np.array([[1, 2], [3, 4], [5, 6]])
vetor3x2

array([[1, 2],
       [3, 4],
       [5, 6]])

In [23]:
vetor3x2.shape

(3, 2)

In [25]:
vetor2x3 = np.array([[1, 2, 3],[4, 5, 6]])
vetor2x3

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
vetor2x3.shape

(2, 3)

In [27]:
y = np.arange(2, 200, 5)
y

array([  2,   7,  12,  17,  22,  27,  32,  37,  42,  47,  52,  57,  62,
        67,  72,  77,  82,  87,  92,  97, 102, 107, 112, 117, 122, 127,
       132, 137, 142, 147, 152, 157, 162, 167, 172, 177, 182, 187, 192,
       197])